
["Spawn Biome Utility Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#generateReport
	generateReport = false
	#suppressMinecraftMobReporting
	suppressMinecraftMobReporting = true
	#fixEmptyNether
	fixEmptyNether = false
	#Use the 'BiomeMobWeight.csv' file to balance Biome spawn values
	balanceBiomeSpawnValues = true
	#Fix min, max values and add nether creatures
	fixSpawnValues = true
	#Use the 'StructMobWeight.csv' file to balance structure spawn values
	balanceStructureSpawnValues = true
	#Mod Name set separated by SemiColons of mods to report.
	includedReportModsSet = "exampleModName;"

["Spawn Placement Fixes"]
	#Add mobs spawning in the air and falling to this list .
	defaultSpawnWeightList = "minecraft:piglin_brute;goblinanddungeon:gob;goblinanddungeon:hobgob;"

["Spawn Weight Values"]
	#minimum Spawn Weight
	#Range: 1 ~ 1000
	minSpawnWeight = 1
	#maximum Spawn Weight
	#Range: 1 ~ 1000
	maxSpawnWeight = 100
	#list of Mod:MobName,DefaultSpawnweight;
	defaultSpawnWeightList = "minecraft:husk,0;minecraft:stray,0;minecraft:panda,0;minecraft:camel,0;minecraft:llama,0;minecraft:trader_llama,0;minecraft:fox,0;minecraft:cat,0;minecraft:tadpole,0;minecraft:frog,0;minecraft:sniffer,0;minecraft:strider,0;quark:forgotten,0;quark:shiba,0;quark:toretoise,0;supplementaries:red_merchant,0;sleep_tight:bedbug,0;"

